version: '3.4'

services:
  web:
    image: velreine/d2d-web:latest
    build:
      context: Door2Door-Web/
      dockerfile: Dockerfile

    environment:
      NODE_ENV: production
      API_URL: "http://192.168.1.102" # Should be IP of the host, as this should be accessible from the client browser.
    ports:
      - 5000:80
      - 5443:443
    networks:
      - frontend
    depends_on:
      - api
  api:
    image: velreine/d2d-api:latest
    build:
      context: Door2Door-API/
      dockerfile: Dockerfile
    ports:
      - 3000:80
      - 3443:443
    networks:
      - backend
      - frontend
    environment:
      CONNECTION_STRING: "Server=192.168.1.102;Port=5432;Database=door2door;User Id=postgres;Password=CHANGE_ME_12345;"
      ASPNETCORE_URLS: "htps://+;http://+"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "foobar"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnet-api.pfx" 
    depends_on:
      - db
  db:
    image: postgis/postgis:13-3.2-alpine
    environment:
      POSTGRES_PASSWORD: CHANGE_ME_12345
    ports:
      - 5432:5432
    networks:
      - backend
networks:
  backend:
  frontend: