version: '3.4'

services:
  web:
    image: velreine/d2d-web:latest
    build:
      context: Door2Door-Web/
      dockerfile: Dockerfile

    environment:
      NODE_ENV: production
    ports:
      - 3000:80
    networks:
      - frontend
    depends_on:
      - api
  api:
    image: velreine/d2d-api:latest
    build:
      context: Door2Door-API/
      dockerfile: Dockerfile
    ports:
      - 5206:80
    networks:
      - backend
      - frontend
    depends_on:
      - db
  db:
    image: postgis/postgis:13-3.2-alpine
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    networks:
      - backend
networks:
  backend:
  frontend: